# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/batuh/qt_designer/exe_deneme2/gırısekran.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 400)
        MainWindow.setMinimumSize(QtCore.QSize(300, 200))
        MainWindow.setMaximumSize(QtCore.QSize(600, 400))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/ıcon/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.formLayout = QtWidgets.QFormLayout(self.frame)
        self.formLayout.setContentsMargins(20, 20, 20, 20)
        self.formLayout.setObjectName("formLayout")
        self.label_ad = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_ad.setFont(font)
        self.label_ad.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_ad.setObjectName("label_ad")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_ad)
        self.kullanci_ad = QtWidgets.QLineEdit(self.frame)
        self.kullanci_ad.setStyleSheet("")
        self.kullanci_ad.setObjectName("kullanci_ad")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.kullanci_ad)
        self.label_sifre = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_sifre.setFont(font)
        self.label_sifre.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_sifre.setObjectName("label_sifre")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_sifre)
        self.kullanici_sifre = QtWidgets.QLineEdit(self.frame)
        self.kullanici_sifre.setObjectName("kullanici_sifre")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.kullanici_sifre)
        self.horizontalLayout_2.addWidget(self.frame)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(75, -1, 20, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.giris_buton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.giris_buton.setFont(font)
        self.giris_buton.setStyleSheet("background-color: rgb(247, 255, 239);\n"
"border -radius : 5px")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/gırısicon/ıcon/girişıcon.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.giris_buton.setIcon(icon1)
        self.giris_buton.setIconSize(QtCore.QSize(50, 30))
        self.giris_buton.setObjectName("giris_buton")
        self.horizontalLayout.addWidget(self.giris_buton)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Kullanıcı Girişi"))
        self.label_ad.setText(_translate("MainWindow", "Ad"))
        self.label_sifre.setText(_translate("MainWindow", "Şifre"))
        self.giris_buton.setText(_translate("MainWindow", "Giriş"))

import icons_rc
