# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gırısekran.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import QLabel
from PyQt5.QtCore import Qt

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 400)
        MainWindow.setMinimumSize(QtCore.QSize(300, 200))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/ıcon/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("#centralwidget{\n"
"border-image: url(:/newPrefix/ıcon/988880.jpg);\n"
"}")

        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(20, 20, 20, 20)
        self.formLayout.setObjectName("formLayout")
        self.label_ad = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_ad.setFont(font)
        self.label_ad.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_ad.setObjectName("label_ad")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_ad)
        self.kullanci_ad = QtWidgets.QLineEdit(self.centralwidget)
        self.kullanci_ad.setStyleSheet("")
        self.kullanci_ad.setObjectName("kullanci_ad")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.kullanci_ad)
        self.label_sifre = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_sifre.setFont(font)
        self.label_sifre.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_sifre.setObjectName("label_sifre")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_sifre)
        self.kullanici_sifre = QtWidgets.QLineEdit(self.centralwidget)
        self.kullanici_sifre.setObjectName("kullanici_sifre")
        self.kullanici_sifre.setEchoMode(QtWidgets.QLineEdit.Password)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.kullanici_sifre)
        self.horizontalLayout_2.addLayout(self.formLayout)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(75, -1, 20, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.giris_buton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.giris_buton.setFont(font)
        self.giris_buton.setStyleSheet("background-color: rgb(247, 255, 239);\n"
"border -radius : 5px")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/gırısicon/ıcon/girişıcon.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.giris_buton.setIcon(icon1)
        self.giris_buton.setIconSize(QtCore.QSize(50, 30))
        self.giris_buton.setObjectName("giris_buton")
        self.horizontalLayout.addWidget(self.giris_buton)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.copyr = QLabel("<u>2020 -- Batuhan Bağ  ©</u>")
        self.copyr.setStyleSheet("color: rgb(255, 255, 255);")
        self.copyr.setAlignment(Qt.AlignHCenter | Qt.AlignBottom)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "User Login BB"))
        self.label_ad.setText(_translate("MainWindow", "Username"))
        self.label_sifre.setText(_translate("MainWindow", "Password"))
        self.giris_buton.setText(_translate("MainWindow", "Login"))











import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
