# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/batuh/qt_designer/exe_deneme2/pencere.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow2(object):
    def setupUi(self, MainWindow2):
        MainWindow2.setObjectName("MainWindow2")
        MainWindow2.resize(800, 600)
        MainWindow2.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow2.setMaximumSize(QtCore.QSize(800, 1080))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../ıcon/indir.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow2.setWindowIcon(icon)
        MainWindow2.setStyleSheet("#centralwidget{\n"
"border-image: url(:/newPrefix/ıcon/988880.jpg);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow2)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setEnabled(True)
        self.stackedWidget.setGeometry(QtCore.QRect(-40, -10, 800, 591))
        self.stackedWidget.setMinimumSize(QtCore.QSize(500, 400))
        self.stackedWidget.setMaximumSize(QtCore.QSize(800, 600))
        self.stackedWidget.setStyleSheet(" #stackedWidget{\n"
"border-image: url(:/newPrefix/ıcon/988880.jpg);\n"
"}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_homepage = QtWidgets.QWidget()
        self.page_homepage.setObjectName("page_homepage")
        self.label_2 = QtWidgets.QLabel(self.page_homepage)
        self.label_2.setGeometry(QtCore.QRect(300, 10, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_6 = QtWidgets.QLabel(self.page_homepage)
        self.label_6.setGeometry(QtCore.QRect(60, 110, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.lineEdit_booknamequery = QtWidgets.QLineEdit(self.page_homepage)
        self.lineEdit_booknamequery.setGeometry(QtCore.QRect(230, 110, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_booknamequery.setFont(font)
        self.lineEdit_booknamequery.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_booknamequery.setObjectName("lineEdit_booknamequery")
        self.pushButton_namequery = QtWidgets.QPushButton(self.page_homepage)
        self.pushButton_namequery.setGeometry(QtCore.QRect(450, 170, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_namequery.setFont(font)
        self.pushButton_namequery.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_namequery.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton_namequery.setIcon(icon)
        self.pushButton_namequery.setObjectName("pushButton_namequery")
        self.label_4 = QtWidgets.QLabel(self.page_homepage)
        self.label_4.setGeometry(QtCore.QRect(320, 230, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.textEdit = QtWidgets.QTextEdit(self.page_homepage)
        self.textEdit.setGeometry(QtCore.QRect(190, 280, 361, 181))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit.setPlaceholderText("")
        self.textEdit.setObjectName("textEdit")
        self.label_15 = QtWidgets.QLabel(self.page_homepage)
        self.label_15.setGeometry(QtCore.QRect(40, 510, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_15.setObjectName("label_15")
        self.stackedWidget.addWidget(self.page_homepage)
        self.page_bookadd = QtWidgets.QWidget()
        self.page_bookadd.setObjectName("page_bookadd")
        self.lineEdit_code = QtWidgets.QLineEdit(self.page_bookadd)
        self.lineEdit_code.setGeometry(QtCore.QRect(170, 60, 461, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_code.setFont(font)
        self.lineEdit_code.setStatusTip("")
        self.lineEdit_code.setWhatsThis("")
        self.lineEdit_code.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_code.setObjectName("lineEdit_code")
        self.lineEdit_bookname = QtWidgets.QLineEdit(self.page_bookadd)
        self.lineEdit_bookname.setGeometry(QtCore.QRect(170, 140, 461, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_bookname.setFont(font)
        self.lineEdit_bookname.setStatusTip("")
        self.lineEdit_bookname.setWhatsThis("")
        self.lineEdit_bookname.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_bookname.setObjectName("lineEdit_bookname")
        self.lineEdit_writer = QtWidgets.QLineEdit(self.page_bookadd)
        self.lineEdit_writer.setGeometry(QtCore.QRect(170, 210, 461, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_writer.setFont(font)
        self.lineEdit_writer.setStatusTip("")
        self.lineEdit_writer.setWhatsThis("")
        self.lineEdit_writer.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_writer.setObjectName("lineEdit_writer")
        self.lineEdit_type = QtWidgets.QLineEdit(self.page_bookadd)
        self.lineEdit_type.setGeometry(QtCore.QRect(170, 290, 461, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_type.setFont(font)
        self.lineEdit_type.setStatusTip("")
        self.lineEdit_type.setWhatsThis("")
        self.lineEdit_type.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_type.setObjectName("lineEdit_type")
        self.lineEdit_edition = QtWidgets.QLineEdit(self.page_bookadd)
        self.lineEdit_edition.setGeometry(QtCore.QRect(170, 360, 461, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_edition.setFont(font)
        self.lineEdit_edition.setStatusTip("")
        self.lineEdit_edition.setWhatsThis("")
        self.lineEdit_edition.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_edition.setObjectName("lineEdit_edition")
        self.label = QtWidgets.QLabel(self.page_bookadd)
        self.label.setGeometry(QtCore.QRect(40, 370, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.label_9 = QtWidgets.QLabel(self.page_bookadd)
        self.label_9.setGeometry(QtCore.QRect(40, 290, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.page_bookadd)
        self.label_10.setGeometry(QtCore.QRect(40, 220, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.page_bookadd)
        self.label_11.setGeometry(QtCore.QRect(40, 140, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.page_bookadd)
        self.label_12.setGeometry(QtCore.QRect(40, 70, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_12.setObjectName("label_12")
        self.pushButton_bookadd = QtWidgets.QPushButton(self.page_bookadd)
        self.pushButton_bookadd.setGeometry(QtCore.QRect(490, 410, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_bookadd.setFont(font)
        self.pushButton_bookadd.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_bookadd.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_bookadd.setIcon(icon)
        self.pushButton_bookadd.setObjectName("pushButton_bookadd")
        self.label_17 = QtWidgets.QLabel(self.page_bookadd)
        self.label_17.setGeometry(QtCore.QRect(330, 10, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_17.setObjectName("label_17")
        self.label_7 = QtWidgets.QLabel(self.page_bookadd)
        self.label_7.setGeometry(QtCore.QRect(0, 0, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(2)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.stackedWidget.addWidget(self.page_bookadd)
        self.page_useradd = QtWidgets.QWidget()
        self.page_useradd.setObjectName("page_useradd")
        self.label_3 = QtWidgets.QLabel(self.page_useradd)
        self.label_3.setGeometry(QtCore.QRect(60, 110, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.label_8 = QtWidgets.QLabel(self.page_useradd)
        self.label_8.setGeometry(QtCore.QRect(60, 230, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.lineEdit_regusername = QtWidgets.QLineEdit(self.page_useradd)
        self.lineEdit_regusername.setGeometry(QtCore.QRect(230, 120, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_regusername.setFont(font)
        self.lineEdit_regusername.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_regusername.setObjectName("lineEdit_regusername")
        self.lineEdit_regpassword = QtWidgets.QLineEdit(self.page_useradd)
        self.lineEdit_regpassword.setGeometry(QtCore.QRect(230, 240, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_regpassword.setFont(font)
        self.lineEdit_regpassword.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_regpassword.setObjectName("lineEdit_regpassword")
        self.pushButton_2 = QtWidgets.QPushButton(self.page_useradd)
        self.pushButton_2.setGeometry(QtCore.QRect(410, 330, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../ıcon/ekle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_13 = QtWidgets.QLabel(self.page_useradd)
        self.label_13.setGeometry(QtCore.QRect(290, 20, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_13.setObjectName("label_13")
        self.stackedWidget.addWidget(self.page_useradd)
        MainWindow2.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow2)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menuPages = QtWidgets.QMenu(self.menubar)
        self.menuPages.setObjectName("menuPages")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow2.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow2)
        self.statusbar.setObjectName("statusbar")
        MainWindow2.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow2)
        self.toolBar.setEnabled(True)
        self.toolBar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toolBar.setMovable(True)
        self.toolBar.setIconSize(QtCore.QSize(35, 100))
        self.toolBar.setObjectName("toolBar")
        MainWindow2.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBar)
        self.actionAdd_Book = QtWidgets.QAction(MainWindow2)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../ıcon/afasfafa.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAdd_Book.setIcon(icon2)
        self.actionAdd_Book.setObjectName("actionAdd_Book")
        self.actionBook_List = QtWidgets.QAction(MainWindow2)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../ıcon/kitapliste.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBook_List.setIcon(icon3)
        self.actionBook_List.setObjectName("actionBook_List")
        self.actionAdd_User = QtWidgets.QAction(MainWindow2)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../ıcon/asfafasf.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAdd_User.setIcon(icon4)
        self.actionAdd_User.setObjectName("actionAdd_User")
        self.action_about = QtWidgets.QAction(MainWindow2)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../icon_exe/about.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_about.setIcon(icon5)
        self.action_about.setObjectName("action_about")
        self.menuPages.addAction(self.actionAdd_Book)
        self.menuPages.addAction(self.actionBook_List)
        self.menuPages.addAction(self.actionAdd_User)
        self.menuHelp.addAction(self.action_about)
        self.menubar.addAction(self.menuPages.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionBook_List)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionAdd_Book)
        self.toolBar.addAction(self.actionAdd_User)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_about)

        self.retranslateUi(MainWindow2)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow2)

    def retranslateUi(self, MainWindow2):
        _translate = QtCore.QCoreApplication.translate
        MainWindow2.setWindowTitle(_translate("MainWindow2", "Library Menu"))
        self.label_2.setText(_translate("MainWindow2", "BOOK QUERY"))
        self.label_6.setText(_translate("MainWindow2", "Book Name :"))
        self.pushButton_namequery.setText(_translate("MainWindow2", "Query"))
        self.label_4.setText(_translate("MainWindow2", "BOOK İNFO"))
        self.label_15.setText(_translate("MainWindow2", "<u>2020 -- Batuhan Bağ v1.0 ©</u>"))
        self.label.setText(_translate("MainWindow2", "Edition :"))
        self.label_9.setText(_translate("MainWindow2", "Type:"))
        self.label_10.setText(_translate("MainWindow2", "Writer:"))
        self.label_11.setText(_translate("MainWindow2", "Book Name:"))
        self.label_12.setText(_translate("MainWindow2", "Book Code:"))
        self.pushButton_bookadd.setText(_translate("MainWindow2", "Add"))
        self.label_17.setText(_translate("MainWindow2", "Book Add"))
        self.label_7.setText(_translate("MainWindow2", "<u>2020 - Batuhan Bağ  ©</u>"))
        self.label_3.setText(_translate("MainWindow2", "Username :"))
        self.label_8.setText(_translate("MainWindow2", "Password :"))
        self.pushButton_2.setText(_translate("MainWindow2", "Add User"))
        self.label_13.setText(_translate("MainWindow2", "User Registration"))
        self.menuPages.setTitle(_translate("MainWindow2", "Pages"))
        self.menuHelp.setTitle(_translate("MainWindow2", "Help"))
        self.toolBar.setWindowTitle(_translate("MainWindow2", "toolBar"))
        self.actionAdd_Book.setText(_translate("MainWindow2", "Add Book"))
        self.actionBook_List.setText(_translate("MainWindow2", "Book List"))
        self.actionAdd_User.setText(_translate("MainWindow2", "Add User "))
        self.action_about.setText(_translate("MainWindow2", "About"))

import icons_rc
